### PR TITLE
Address mixed dimensionality in wkt

### PR DESCRIPTION
**Pull request by eseglem**
## What I am changing

- Addressing mixed dimensionality edge case on WKT functions.

## How I did it

- Add capability to `force_z` in wkt functions.
- Use `has_z` to determine when to force the inclusion of z.
- Adjust signatures to work together. 

## How you can test it

- All the current tests still work. 

## Related Issues

- #102 

---

It was a bit weirder than I wanted to only run `has_z` once at the top level. I iterated way too many times on figuring out the best way to set the wkt coordinate functions at the class level. I think I am finally OK with how its set up. 

- [x] Add tests specific to mixed dimensions. 
- [x] Verify how `Z` is used on GeometryCollection in spec and adjust if needed. (Maybe wait for follow on PR?) 
- ~~Move helper functions to `wkt.py`?~~

### CODE REVIEW

**Comment by vincentsarago** [comment]
👋 @eseglem I'm picking up my TODO list This week 😄 is there something more to do in this PR?

**Comment by eseglem** [comment]
Yeah, I just got distracted working on a few other things. I thankfully left myself a checklist of things needed in the PR. Mostly wanted to add some tests specifically with mixed dimensionality in them. 

And probably check on Z in GeometryCollection and how shapely ends up handling those situations. Like if you have `POINT (0 0)` and `LINESTRING Z (0 0 0, 1 1 1)` what happens when you put them together in a GeometryCollection together. Just haven't gotten a chance to check it yet.

**Comment by eseglem** [comment]
Interesting this is what it does:

```
>>> shapely.GeometryCollection([shapely.Point(0,0), shapely.LineString([(0,0,0),(1,1,1)])]).wkt
'GEOMETRYCOLLECTION Z (POINT (0 0), LINESTRING Z (0 0 0, 1 1 1))'
```

So I matched that behavior.

**Comment by eseglem** [comment]
There is a question about if its worth breaking out all those helper functions that are at the top of `geometries.py` into a separate `wkt.py` to clean things up a bit. ~22-75 area. But thinking that may be something to do in a separate PR if so?

**Comment by vincentsarago** [comment]
>  But thinking that may be something to do in a separate PR if so

Yes let's do this another PR

**Comment by vincentsarago** [comment]
🙏 thank you

**Pull request merged**
