### PR TITLE
feat: add generics to feature properties

### PR DESCRIPTION
**Pull request by iwpnd**
Hi!

First of all sorry for the unsolicited PR. 

I wanted to start a project similar to this but luckily I researched up front. Something was missing for me, and I kinda jumped on the idea to add generics to feature properties and it turned out quite okay right away.

The idea is, that instead of using a `Dict[Any, Any]` for the feature properties, you can opt to pass a model to `Feature` that is then parsed just like e.g. the `Geometry`.

This allows you, among other things, to validate feature properties in a Feature. Even cooler, it is not even a must. You can use it just like you are doing right now, but give the option to also parse the `properties`.

Example:

```python
from pydantic import BaseModel
from geojson_pydantic import Feature

class MyFeatureProperties(BaseModel):
    id: str
    description: str

feature = Feature[MyFeatureProperties](**{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [13.38272,52.46385],
        [13.42786,52.46385],
        [13.42786,52.48445],
        [13.38272,52.48445],
        [13.38272,52.46385]
      ]
    ]
  },
  "properties": {
    "id": "test",
    "description": "i will be parsed"
  }
})

print(isinstance(feature.properties, MyFeatureProperties))
>> True
```

Let me know what you think.

### CODE REVIEW

**Comment by geospatial-jeff** [comment]
I was not aware that pydantic supported generics, this is really cool, I think a good feature to add.

**Comment by drewbo** [comment]
Really like this and agree that this is preferable to the model factory pattern. cc: @vincentsarago for thoughts

**Comment by geospatial-jeff** [comment]
I'm also fine dropping support for python 3.6

**Comment by iwpnd** [comment]
I allowed edits by the maintainer @vincentsarago

**Comment by vincentsarago** [comment]
>  #28 adds similar functionality for exposing the Feature's geometry type, but using pydantic's create_model instead. I think we should use either one or the other (generics / create_model), not both. Generics seem more explicit to me.

@geospatial-jeff I agree we shouldn't use both but I'm not sure there is an easy way to allow `dynamic` modelling for geometry and properties using `Generics` 🤷‍♂️ 

FYI: I'm going to `un-approve` this PR for now even if the whole code is A+ and it does what advertised, but because it is in conflict with #28

**Comment by vincentsarago** [comment]
@iwpnd so what we wanted with #28 was to create model that only validate Polygon Feature for example as explained in https://github.com/developmentseed/geojson-pydantic/issues/20#issuecomment-752669782

**Comment by iwpnd** [comment]
Okay. So something like that:

```python
from typing import TypeVar, Generic, Dict
from pydantic.generics import GenericModel, BaseModel
from geojson_pydantic.geometries import Geometry, Polygon

Props = TypeVar('Props', bound=Dict)
Geom = TypeVar('Geom', bound=Geometry)

class Feature(GenericModel, Generic[Geom, Props]):
    type: str = 'Feature'
    geometry: Geom
    properties: Props
        
class MyFeatureProperties(BaseModel):
    id: str
    description: str

feature = Feature[Polygon, MyFeatureProperties](**{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [13.38272,52.46385],
        [13.42786,52.46385],
        [13.42786,52.48445],
        [13.38272,52.48445],
        [13.38272,52.46385]
      ]
    ]
  },
  "properties": {
    "id": "test",
    "description": "i will be parsed"
  }
})
```

Where this passes as you'd expect it to do.

And 

```python
feature = Feature[Polygon, MyFeatureProperties](**{
  "type": "Feature",
  "geometry": {
    "type": "Cheese",
    "coordinates": [
      [
        [13.38272,52.46385],
        [13.42786,52.46385],
        [13.42786,52.48445],
        [13.38272,52.48445],
        [13.38272,52.46385]
      ]
    ]
  },
  "properties": {
    "id": "test",
    "description": "i will be parsed"
  }
})
```

raises:

```python
ValidationError: 1 validation error for Feature[Polygon, MyFeatureProperties]
geometry -> type
  unexpected value; permitted: 'Polygon' (type=value_error.const; given=Cheese; permitted=['Polygon'])
```

**Comment by vincentsarago** [comment]
yes but does `Feature[MyFeatureProperties]` work still ?

**Comment by iwpnd** [comment]
> yes but does `Feature[MyFeatureProperties]` work still ?

Only if you take it one step further

```python
class Feature(GenericModel, Generic[Geom, Props]):
    type: str = 'Feature'
    geometry: Union[Geom, Geometry] = Geometry
    properties: Props
        
class MyFeatureProperties(BaseModel):
    id: str
    description: str

feature = Feature[None, MyFeatureProperties](**{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [13.38272,52.46385],
        [13.42786,52.46385],
        [13.42786,52.48445],
        [13.38272,52.48445],
        [13.38272,52.46385]
      ]
    ]
  },
  "properties": {
    "id": "test",
    "description": "i will be parsed"
  }
})
```

But this is kind off drifting away from the scope of this PR, I guess.

**Comment by iwpnd** [comment]
Do you want to move forward with this? I'd be happy to spend some more time to make this work for you. Otherwise I'd be closing this PR and create a fork for my use-case.

**Comment by vincentsarago** [comment]
Hi @iwpnd 
Sorry to let this slip through, I had other priorities last week. I'll try to work on this this week but I can't make promises. If you can't wait go ahead and create a fork 👍

**Comment by iwpnd** [comment]
Hi @vincentsarago, re-reading my comment I didn't mean to come across as pushy as it turned out. If you're saying you're still considering it, I'm okay.

**Comment by vincentsarago** [comment]
@iwpnd so I'm trying to add Generic for Geom and Props as 
```python
Props = TypeVar('Props', bound=Dict)
Geom = TypeVar('Geom', bound=Geometry)


class Feature(GenericModel, Generic[Geom, Props]):
    """Feature Model"""

    type: str = Field("Feature", const=True)
    geometry: Geom
    properties: Optional[Props]
    id: Optional[str]
    bbox: Optional[BBox]
```

```python
Feature[Polygon, None](**f)
>>> ValidationError: 1 validation error for Feature[Polygon, NoneType]
properties
  value is not None (type=type_error.not_none)

Feature[None, MyFeatureProperties](**f)
>>> ValidationError: 1 validation error for Feature[NoneType, MyFeatureProperties]
geometry
  value is not None (type=type_error.not_none)
``` 

To be able to use `MyFeatureProperies` it seems to me that you'll have to pass `geojson_pydantic.geometry.Geometry` as the first input.

IMO this is not optimal, and `create_model` might be easier (because you can have defaults) 

cc @geospatial-jeff

**Comment by vincentsarago** [comment]
After talking with @geospatial-jeff (on slack) I agree that's it's ok to being forced to provide both types (geom and props) 

```python
feat = Feature[Polygon, Dict]
feat = Feature[Geom, MyPropsModel]
```

I'm going to update this PR and wait for feedback

**Comment by vincentsarago** [comment]
I have added `Geometry` generic in addition to the Props generic. 


Please 👍 👎 


cc @geospatial-jeff @drewbo @iwpnd

**Review by vincentsarago — APPROVED** [review]

**Pull request merged**
